version: '3.8'
services:
  # webgraph-openapi-backend:
  #   build:
  #     context: ../backend/docker
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 5435:5432
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #     TZ: "Europe/Rome"
  #   volumes:
  #     - /graphs:/usr/graphs
  webgraph-openapi-frontend:
    build:
      args: []
      context: ../frontend
      dockerfile: docker/Dockerfile
    restart: always
    # depends_on:
    #   - backend
    ports:
        - 8801:80