services:
  webgraph-openapi-backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    restart: always
    container_name: webgraph-openapi-backend
    environment:
      - ROCKET_ADDRESS="0.0.0.0"  # Listen on all interfaces
      - ROCKET_PORT=8000
      - BASE_MEMSIZE=25
      - RUST_BACKTRACE=1
    ports:
      - 8801:8000
    volumes:
      - /Users/mn/Developer/working-copies/uni/avgdist-rs/data/star:/usr/webgraphs/star      
      - /Users/mn/Developer/bitcoin/ag:/usr/webgraphs/ag
      - /Users/mn/Developer/bitcoin/atg:/usr/webgraphs/atg
      - /Users/mn/Developer/bitcoin/pg:/usr/webgraphs/pg
      - /Users/mn/Developer/bitcoin/ug:/usr/webgraphs/ug
      - /Users/mn/Developer/bitcoin/tg:/usr/webgraphs/tg

  webgraph-openapi-frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    restart: always
    container_name: webgraph-openapi-frontend
    depends_on:
      - webgraph-openapi-backend
    ports:
      - 8800:80
    environment:
      - TOPIC_NAME="pg"
      - GRAPH_NAME="pg"

  neo4j-bitcoin:
    # image: neo4j:enterprise
    image: neo4j:5.18.0-enterprise
    restart: always
    container_name: webgraph-openapi-neo4j-bitcoin
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ../../neo4j/paymentsgraph/data:/data