services:
  webgraph-openapi-backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    restart: always
    container_name: webgraph-openapi-backend
    environment:
      - ROCKET_ADDRESS="0.0.0.0"  # Listen on all interfaces
      - ROCKET_PORT=8000
    ports:
      - 8801:8000
    volumes:
      - /Users/mn/Developer/working-copies/uni/avgdist-rs/data/star:/usr/webgraphs/star
      - /Volumes/Data/bitcoin:/usr/webgraphs/bitcoin
      - /home/mn/Developer/working-copies/personal/development-snapshots.sh/working-copies/rust/avgdist-rs/data/star:/usr/webgraphs/star
      - /home/mn/Downloads/bitcoin-graphs/Bitcoin_Graphs/pg:/usr/webgraphs/pg
      - /home/mn/Downloads/bitcoin-graphs/Bitcoin_Graphs/ag:/usr/webgraphs/ag

  webgraph-openapi-frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    restart: always
    container_name: webgraph-openapi-frontend
    depends_on:
      - webgraph-openapi-backend
    ports:
      - 8800:80
    environment:
      - TOPIC_NAME="pg"
      - GRAPH_NAME="pg"
