services:
  webgraph-openapi-backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    restart: always
    container_name: webgraph-openapi-backend
    ports:
      - 8000:8000
    volumes:
      - /graphs:/usr/graphs



  webgraph-openapi-frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    restart: always
    container_name: webgraph-openapi-frontend
    depends_on:
      - webgraph-openapi-backend
    ports:
      - 8800:80
