[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
webgraph = { git = "https://github.com/vigna/webgraph-rs" }


[dependencies.rocket]
version = "0.5.1"
features = ["json", "msgpack", "uuid"]
